spring.application.name=ApiGateway

server.port=8085
jwt.secret=kjsadfh4rkjenfmdsbw84jvrbn3484bssdvb8943ferjnvndenv849bvniuf3489


# =========================
# SERVICE 1 ROUTE
# =========================
spring.cloud.gateway.routes[0].id=service1
spring.cloud.gateway.routes[0].uri=lb://SERVICE1
spring.cloud.gateway.routes[0].predicates[0]=Path=/service1/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=Authentication


# =========================
# SERVICE 2 ROUTE
# =========================
spring.cloud.gateway.routes[1].id=service2
spring.cloud.gateway.routes[1].uri=lb://SERVICE2
spring.cloud.gateway.routes[1].predicates[0]=Path=/service2/**
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=X-Service-Name, Ritesh
spring.cloud.gateway.routes[1].filters[2]=LoggingorderFilter
spring.cloud.gateway.routes[1].filters[3]=Authentication


# Optional: Remove prefix (/service2)
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

logging.level.org.springframework.cloud.gateway=DEBUG
